jobs:

  - name: selenium-test-man-1
    type: manifest
    steps:
      - IN: hub-1
      - IN: hub-opts-1
        applyTo:
          - hub
      - IN: firefox-node-img-1
      - IN: chrome-node-img-1
      - IN: chrome-node1-img-1
      - IN: selenium-img-1
      - IN: link-opts
        applyTo:
          - firefox-node-img-1
          - chrome-node-img-1
          - chrome-node1-img-1
          - selenium-img-1
      - TASK: managed
    flags:
      - ram-test-selenium

  - name: selenium-ecs-deploy-1
    type: deploy
    steps:
      - IN: selenium-test-man-1
      - IN: selenium-clu-1
      - TASK: managed
        deployMethod: upgrade